[package]
name = "docbert"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A powerful semantic search CLI for your documents"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
redb = "3.1.0"
xdg = "3.0.0"
